### PR TITLE
Use npm's own module to obtain the paths

### LINKED ISSUE #2: irish-pub invokes prepublish script and fails
Consider this `package.json`:

``` json
{
  "name": "example",
  "version": "0.0.0",
  "scripts": {
    "prepublish": "echo prepublished"
  }
}
```

`irish-pub` should not `npm pack` to obtain the list of files as it will run `prepublish`.

```
$ irish-pub
npm publish will include the following files:

{ [Error: ENOENT, open '/tmp/example/> example@0.0.0 prepublish /tmp/example
> echo prepublished

prepublished
example-0.0.0.tgz']
  errno: 34,
  code: 'ENOENT',
  path: '/tmp/example/> example@0.0.0 prepublish /tmp/example\n> echo prepublished\n\nprepublished\nexample-0.0.0.tgz' }
```

### PR DESCRIPTION
**Pull request by eush77**
This PR fixes #2 by switching to completely different method of solving the problem. Instead of packing a tarball and then inspecting it, this version uses [the module](https://www.npmjs.com/package/fstream-npm) responsible to do [the same job](https://github.com/npm/npm/blob/7f6557ff317469ee4a87c542ff9a991e74ce9f38/lib/utils/tar.js#L47-75) in npm itself.

As a bonus, it also takes significantly less time compared to the master version due to reduced disk IO utilization.

Path processing logic was constructed to revert [these lines](https://github.com/npm/fstream-npm/blob/4a95e1903f93dc122320349bb55e367ddd08ad6b/fstream-npm.js#L304-307).

### CODE REVIEW

**Comment by eush77** [comment]
As @ljharb [pointed out](https://github.com/thlorenz/irish-pub/issues/2#issuecomment-66908721), `prepublish` script should be run anyway (if there is one). I will update this PR shortly.

**Comment by eush77** [comment]
ping @thlorenz

**Comment by thlorenz** [comment]
Interesting, I think @timoxley has a module that already does it this way.

> prepublish script should be run anyway (if there is one)

Not sure about that. This is intended as a _dry-run_. If I just want to check something I don't expect any scripts that change the state of my module to run as well.

Also please separate into two PRs, each adding/changing one feature.
First two commits should be one, last two another one. 

You can just remove last two commits from this one and create another PR for those last two.

**Comment by timoxley** [comment]
yep: https://github.com/timoxley/pkgfiles

Note though that mine takes it a step further, rather than just requiring whatever version of `fstream-npm` happens to be bundled into `irish-pub`, `pkgfiles` [extracts the exact fstream-npm](https://github.com/timoxley/pkgfiles/blob/562799d3effa3081877f8fc3457b55bce76f2bd3/index.js#L12) that the npm-cli uses via some sneaky business in [pkgresolve](https://github.com/timoxley/pkgresolve).

``` js
var resolve = require('pkgresolve')
// …
function pkgFiles(dir, fn) {
  resolve('fstream-npm').fromGlobal('npm', function(err, fstreamPath) {
    // …
  })
})
```

This necessary because there's a good chance that if the `fstream-npm` versions differ, the files they include will differ thus making the whole endeavour pointless.

**Comment by thlorenz** [comment]
Ok, so seems to me that having two modules using different algos is more useful than just duplicating.
This way users can choose which they prefer. So let's not use fs-stream in here but instead point at `pkgfiles` in the readme as an alternative.

Gonna close this for now mainly cause it's doing too much in one PR and I don't want to merge first half of it.

If you feel strongly about running prepublish please provide this via another PR @eush77.
I'm open to this as long as it isn't the default but gets turned on via a flag instead.

**Comment by ljharb** [comment]
@thlorenz I agree that the module shouldn't change states as a result of running `irish-pub` - but, you can't possibly know what will actually be published unless you include build artifacts that a `prepublish` script might generate. For example, the `es7-shim` browserifies itself and adds a `dist/es7-shim.js` file on `prepublish`, specifically so it will be included only in the `npm` tarball.

**Comment by thlorenz** [comment]
@ljharb agreed, which is why I'm open to allow this feature via a flag.

**Comment by eush77** [comment]
@thlorenz

> Also please separate into two PRs, each adding/changing one feature.
> First two commits should be one, last two another one. 

Last two commits on this branch do not introduce any new features compared to the master.
`npm pack` itself [runs](https://github.com/npm/npm/blob/051c4738486a826300f205b71590781ce7744f01/lib/utils/tar.js#L37-41) `npm prepublish` script (see also #2), and so I was trying to emulate this behavior for consistency here.

> This is intended as a dry-run. If I just want to check something I don't expect any scripts that change the state of my module to run as well.

Then this module needs some work. I'm not sure how would you do that without digging into how npm works internally and probably coming down to using `fstream-npm` anyway ;)

**Pull request closed without merging**
