### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vweevers**
Updated `tap` to see if it fixes the timeout issue on Travis and added node 4-6.

### CODE REVIEW

**Comment by vweevers** [comment]
Okay, still fails, but at least it shows the culprit now, namely `npm whoami`.

**Comment by vweevers** [comment]
Using a mock registry fixes the tests on all but node 0.8, which doesn't have `server.unref()`. Could add a teardown instead of using `unref`, but 0.8 is pretty ancient so might as well drop it. WDYT @thlorenz?

**Comment by thlorenz** [comment]
Way too much going on in this one PR.
Please provide separate ones, one relating to the tests and tap, another one for the whoami addition.
Thanks

**Comment by chinesedfan** [comment]
@vweevers Can you pick up this PR or do you mind I separate whoami-related code into a new PR?

**Comment by vweevers** [comment]
> Can you pick up this PR or do you mind I separate whoami-related code into a new PR?

Go ahead and make a new PR, copy the code if it's still useful.

**Pull request closed without merging**
